version: "3.8"
services:
  express-video:
    container_name: express-video
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/project
      - node_modules:/project/node_modules/

volumes:
  node_modules: